--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Kylan1940/HealAndFeed
build-by-default: true
branches:
- main
projects:
  HealAndFeed:
    path: ""
    icon: "icon.png"
    libs:
    - src: https://poggit.pmmp.io/ci/supercrafter333/libPiggyEconomy/libPiggyEconomy
...
