name: HealAndFeed
version: 2.1.0
main: Kylan1940\HealAndFeed\Main
api: 4.0.0
author: Kylan1940
defend:
- PurePerms
- EconomyAPI

commands:
  heal:
    description: "Added max player health"
    permission: "healandfeed-heal.command"
  feed:
    description: "Restore hunger player and hunger saturation player"
    permission: "healandfeed-feed.command"
  healfeed:
    description: "HealAndFeedUI"
    permission: "healandfeed-ui.command"
    
permissions:
  healandfeed-heal.command:
    description: "Permission for heal command"
    default: op
  healandfeed-feed.command:
    description: "Permission for feed command"
    default: op
  healandfeed-ui.command:
    description: "Permission for HealAndFeed UI command"
    default: op
