name: HealAndFeed
version: 2.3.0
main: Kylan1940\HealAndFeed\Main
api: 4.0.0
author: Kylan1940
depend:
- PurePerms
softdepend:
- BedrockEconomy

commands:
  heal:
    description: "Add max player health"
    permission: "healandfeed-heal.command"
  feed:
    description: "Restore hunger player and hunger saturation player"
    permission: "healandfeed-feed.command"
  healfeed:
    description: "HealAndFeedUI"
    permission: "healandfeed-ui.command"
    
permissions:
  healandfeed-heal.command:
    description: "Permission for heal command"
    default: op
  healandfeed-feed.command:
    description: "Permission for feed command"
    default: op
  healandfeed-ui.command:
    description: "Permission for HealAndFeed UI command"
    default: op
