# HEAL AND FEED CONFIGURATION
#
# HELP:
# \n for new line
# § for color and special symbols
#
# Message:
message-heal: "§aYou've been healed"
message-feed: "§aYou're full"
#
# UI:
title: "§aHeal§7And§9Feed"
button-heal: "§aHeal"
button-feed: "§9Feed"