# ===========================================================================
# ██╗░░██╗██╗░░░██╗██╗░░░░░░█████╗░███╗░░██╗░░███╗░░░█████╗░░░██╗██╗░█████╗░
# ██║░██╔╝╚██╗░██╔╝██║░░░░░██╔══██╗████╗░██║░████║░░██╔══██╗░██╔╝██║██╔══██╗
# █████═╝░░╚████╔╝░██║░░░░░███████║██╔██╗██║██╔██║░░╚██████║██╔╝░██║██║░░██║
# ██╔═██╗░░░╚██╔╝░░██║░░░░░██╔══██║██║╚████║╚═╝██║░░░╚═══██║███████║██║░░██║
# ██║░╚██╗░░░██║░░░███████╗██║░░██║██║░╚███║███████╗░█████╔╝╚════██║╚█████╔╝
# ╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚══════╝░╚════╝░░░░░░╚═╝░╚════╝░
# ===========================================================================
# Report Plugin: https://github.com/Kylan1940/HealAndFeed/issues/new
# ===========================================================================
# Website: https://web.kylan1940.online
# Donate:
# - https://trakteer.id/Kylan1940 (Indonesian)
# - https://ko-fi.com/Kylan1940
# ===========================================================================


# HEAL AND FEED CONFIGURATION
#
# HELP:
# \n for new line
# § for color and special symbols

# Config Version
# DON'T CHANGE THIS!!! 
config-version: "6" 

# Command:
no-permission:
  heal: "§cYou don't have §aHeal Command §cpermission"
  feed: "§cYou don't have §aFeed Command §cpermission"
  ui: "§cYou don't have §aHealAndFeed UI Command §cpermission"
  healother: "§cYou don't have §aHeal Other Player Command §cpermission"
  feedother: "§cYou don't have §aFeed Other Player Command §cpermission"
  healall: "§cYou don't have §aHeal All Command §cpermission"
  feedall: "§cYou don't have §aFeed All Command §cpermission"
console-command:
  heal: "§c/heal is heal for playerself and only in-game, for console you must /heal (playerOnline)"
  feed: "§c/feed is feed for playerself and only in-game, for console you must /feed (playerOnline)"
  ui: "§c/healfeed is only in-game"

# Message:
message:
  heal: "§aYou've been healed"
  feed: "§aYou're full"
  healall: "§aHeal all players successfully"
  feedall: "§aFeed all players successfully"
no-player:
  found: "§cThis player does not exist"
  online: "§cThere are no online players in server"

# UI
ui:
  title: "§aHeal§7And§cFeed"
  button: 
    heal: "§aHeal"
    feed: "§cFeed"